[project]
name = 'backend'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.indentity]
path = 'contracts/indentity.clar'
clarity_version = 1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
